"""
Keys for cdf files organised by instrument type.
"""


class Instrument:
    def __init__(self):
        self.X_UNIT = ""
        self.Y_UNIT = ""
        self.TIME_CONVERSION = 1
        self.ERROR_LOG = ""
        self.AD_SAMPLING_RATE = ""
        self.AD_COADDITION_FACTOR = ""
        self.TIME_KEY = ""
        self.SCAN_DURATION = ""
        self.INTER_SCAN_TIME = ""
        self.RESOLUTION = ""
        self.ACTUAL_SCAN_NUMBER = ("",)
        self.TIC_KEY = ""
        self.MASS_RANGE_MIN = ""
        self.MASS_RANGE_MAX = ""
        self.TIME_RANGE_MIN = ""
        self.TIME_RANGE_MAX = ""
        self.SCAN_INDEX_KEY = ""
        self.POINT_COUNT_KEY = ""
        self.FLAG_COUNT = ""
        self.MZ_KEY = ""
        self.MS_INTENSITY_KEY = ""
        self.INSTRUMENT_NAME = ""
        self.INSTRUMENT_ID = ""
        self.INSTRUMENT_MFR = ""
        self.INSTRUMENT_MODEL = ""
        self.INSTRUMENT_SERIAL_NO = ""
        self.INSTRUMENT_SW_VERSI = ""
        self.INSTRUMENT_FW_VERSION = ""
        self.INSTRUMENT_OS_VERSION = ""
        self.INSTRUMENT_APP_VERSION = ""
        self.INSTRUMENT_COMMENTS = ""


class JEOL(Instrument):
    def __init__(self):
        self.X_UNIT = "total ion counts"
        self.Y_UNIT = "min."
        self.TIME_CONVERSION = 60
        self.ERROR_LOG = "error_log"
        self.AD_SAMPLING_RATE = "a_d_sampling_rate"
        self.AD_COADDITION_FACTOR = "a_d_coaddition_factor"
        self.TIME_KEY = "scan_acquisition_time"
        self.SCAN_DURATION = "scan_duration"
        self.INTER_SCAN_TIME = "inter_scan_time"
        self.RESOLUTION = "resolution"
        self.ACTUAL_SCAN_NUMBER = ("actual_scan_number",)
        self.TIC_KEY = "total_intensity"
        self.MASS_RANGE_MIN = "mass_range_min"
        self.MASS_RANGE_MAX = "mass_range_max"
        self.TIME_RANGE_MIN = "time_range_min"
        self.TIME_RANGE_MAX = "time_range_max"
        self.SCAN_INDEX_KEY = "scan_index"
        self.POINT_COUNT_KEY = "point_count"
        self.FLAG_COUNT = "flag_count"
        self.MZ_KEY = "mass_values"
        self.MS_INTENSITY_KEY = "intensity_values"
        self.INSTRUMENT_NAME = "instrument_name"
        self.INSTRUMENT_ID = "instrument_id"
        self.INSTRUMENT_MFR = "instrument_mfr"
        self.INSTRUMENT_MODEL = "instrument_model"
        self.INSTRUMENT_SERIAL_NO = "instrument_serial_no"
        self.INSTRUMENT_SW_VERSI = "instrument_sw_versi on"
        self.INSTRUMENT_FW_VERSION = "instrument_fw_version"
        self.INSTRUMENT_OS_VERSION = "instrument_os_version"
        self.INSTRUMENT_APP_VERSION = "instrument_app_version"
        self.INSTRUMENT_COMMENTS = "instrument_comments"
