[package]
name = "chromate"
version = "0.1.0"
edition = "2021"

[lib]
name = "chromate"
path = "rust_src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module"] , default = ["extension-module"]}
