# A code for the data set
dataset = "example_dataset_name"
# Values of the series covered by the chromatograms
series_values = [10.0, 20.0, 30.0]
# Chromatogram filenames in the same order as series_values
chromatograms = ["chrom_001.csv", "chrom_002.csv", "chrom_003.csv"]
# Unit for the chromatogram series.
series_unit = "time/ s"

[conditions]
dihydroxyacetone = [2.0, "M"]
formaldehyde = [2.0, "M"]
NaOH = [0.12, "M"]
CaCl2 = [0.06, "M"]
water = [0.0, "M"]

